const listeQuestion = [
  /* Chimie */
  {
    question: "Quel est le symbole chimique du Fer ?",
    reponse1: "Si",
    reponse2: "Fe",
    reponse3: "O",
    reponse4: "Mn",
    reponse: 2,
    explication: "Le Fer a pour symbole chimique Fe (du latin Ferrum). Si est le Silicium, O l'Oxygène et Mn le Manganèse.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "De quels éléments principaux est composé l'acier ?",
    reponse1: "Cuivre et Zinc",
    reponse2: "Aluminium et Carbone",
    reponse3: "Fer et Carbone",
    reponse4: "Fer et Nickel",
    reponse: 3,
    explication: "L'acier est un alliage dont le constituant principal est le Fer, avec une faible teneur en Carbone (inférieure à 2,11 %).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Le laiton est principalement un alliage de quels métaux ?",
    reponse1: "Cuivre et Étain",
    reponse2: "Fer et Aluminium",
    reponse3: "Plomb et Nickel",
    reponse4: "Cuivre et Zinc",
    reponse: 4,
    explication: "Le laiton est composé de Cuivre et de Zinc. Ne pas confondre avec le Bronze qui associe Cuivre et Étain.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le composant principal du bronze ?",
    reponse1: "Le Cuivre (allié à l'Étain)",
    reponse2: "Le Zinc (allié au Fer)",
    reponse3: "Le Nickel (allié à l'Aluminium)",
    reponse4: "Le Titane (allié au Chrome)",
    reponse: 1,
    explication: "Le bronze historique est constitué majoritairement de Cuivre allié avec de l'Étain.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "À partir de quel taux de carbone un alliage Fer-Carbone est-il considéré comme de la fonte ?",
    reponse1: "0,5 %",
    reponse2: "2,11 %",
    reponse3: "1,2 %",
    reponse4: "5,5 %",
    reponse: 2,
    explication: "La frontière théorique du diagramme Fer-Carbone est à 2,11 %. En dessous c'est de l'acier, au-dessus c'est de la fonte.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel élément chimique donne à l'acier inoxydable sa résistance à la rouille ?",
    reponse1: "Le Carbone (au moins 5 %)",
    reponse2: "Le Silicium (au moins 12 %)",
    reponse3: "Le Chrome (au moins 10,5 %)",
    reponse4: "Le Manganese (au moins 8 %)",
    reponse: 3,
    explication: "Il faut au minimum 10,5 % de Chrome pour former la couche d'oxyde passive qui rend l'acier inoxydable.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Tungstène, métal utilisé pour les électrodes TIG ?",
    reponse1: "Tu",
    reponse2: "Tg",
    reponse3: "Tn",
    reponse4: "W",
    reponse: 4,
    explication: "Le Tungstène a pour symbole W (de son nom allemand / suédois Wolfram).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel gaz est le principal responsable de la corrosion (rouille) de l'acier ?",
    reponse1: "L'Oxygène ($O_2$)",
    reponse2: "L'Azote ($N_2$)",
    reponse3: "L'Argon ($Ar$)",
    reponse4: "L'Hélium ($He$)",
    reponse: 1,
    explication: "La rouille est une réaction d'oxydation : l'Oxygène de l'air (combiné à l'humidité) réagit avec le Fer pour former des oxydes de fer.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Cuivre ?",
    reponse1: "Cr",
    reponse2: "Cu",
    reponse3: "Co",
    reponse4: "Cp",
    reponse: 2,
    explication: "Le Cuivre s'écrit Cu. Cr est le Chrome, Co le Cobalt.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Zinc ?",
    reponse1: "Z",
    reponse2: "Zi",
    reponse3: "Zc",
    reponse4: "Zn",
    reponse: 4,
    explication: "Le symbole du Zinc est Zn.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique de l'Étain ?",
    reponse1: "Sn",
    reponse2: "Et",
    reponse3: "Es",
    reponse4: "Ta",
    reponse: 1,
    explication: "L'Étain se note Sn (du latin Stannum).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Nickel ?",
    reponse1: "Nk",
    reponse2: "Nc",
    reponse3: "Ni",
    reponse4: "N",
    reponse: 3,
    explication: "Le Nickel a pour symbole Ni. N seul désigne l'Azote (Nitrogen).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Titane ?",
    reponse1: "Tt",
    reponse2: "Tn",
    reponse3: "Ta",
    reponse4: "Ti",
    reponse: 4,
    explication: "Le symbole du Titane est Ti.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Plomb ?",
    reponse1: "Pl",
    reponse2: "Pb",
    reponse3: "Po",
    reponse4: "Pm",
    reponse: 2,
    explication: "Le Plomb s'écrit Pb (du latin Plumbum).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel élément d'alliage améliore la trempabilité de l'acier et sa résistance à chaud ?",
    reponse1: "Le Molybdène (Mo)",
    reponse2: "Le Nickel (Ni)",
    reponse3: "Le Tungstène (W)",
    reponse4: "Le Titane (Ti)",
    reponse: 1,
    explication: "Le Molybdène (Mo) augmente la dureté à chaud et évite la fragilité de revenu.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "L'acier dit '18/10' contient 18 % de Chrome et 10 % de quel autre métal ?",
    reponse1: "Zinc",
    reponse2: "Cuivre",
    reponse3: "Nickel",
    reponse4: "Aluminium",
    reponse: 3,
    explication: "Un acier inox 18/10 contient 18 % de Chrome (pour la corrosion) et 10 % de Nickel (pour la stabilité de la structure austénitique).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Comment s'appelle la couche d'oxyde protectrice qui se forme naturellement sur l'acier inox ?",
    reponse1: "La calamine",
    reponse2: "La couche passive",
    reponse3: "La couche de rouille",
    reponse4: "Le laitier",
    reponse: 2,
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel composé chimique forme la rouille classique sur le fer ?",
    reponse1: "Sulfate de cuivre",
    reponse2: "Chlorure de sodium",
    reponse3: "Carbonate de calcium",
    reponse4: "Oxyde de fer",
    reponse: 4,
    explication: "La rouille est chimiquement de l'Oxyde de Fer hydraté ($Fe_2O_3 \cdot nH_2O$).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel élément chimique est considéré comme une impureté fragilisante dans l'acier ?",
    reponse1: "Le Chrome (Cr)",
    reponse2: "Le Soufre (S)",
    reponse3: "Le Nickel (Ni)",
    reponse4: "Le Vanadium (V)",
    reponse: 2,
    explication: "Le Soufre (tout comme le Phosphore) crée des inclusions fragilisantes à chaud (fissuration à chaud).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Le bronze d'aluminium est un alliage composé principalement de cuivre et de :",
    reponse1: "Aluminium",
    reponse2: "Zinc",
    reponse3: "Étain",
    reponse4: "Nickel",
    reponse: 1,
    explication: "Le bronze d'aluminium remplace l'étain par l'Aluminium pour offrir une grande résistance mécanique et à la corrosion.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel métal possède la plus haute conductivité électrique à température ambiante ?",
    reponse1: "L'Or (Au)",
    reponse2: "Le Cuivre (Cu)",
    reponse3: "L'Aluminium (Al)",
    reponse4: "L'Argent (Ag)",
    reponse: 4,
    explication: "L'Argent (Ag) est le meilleur conducteur électrique, suivi de très près par le Cuivre.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Manganèse ?",
    reponse1: "Mg",
    reponse2: "Ma",
    reponse3: "Mn",
    reponse4: "Me",
    reponse: 3,
    explication: "Le Manganèse s'écrit Mn. Mg est le Magnésium.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Magnésium ?",
    reponse1: "Mn",
    reponse2: "Mg",
    reponse3: "Ms",
    reponse4: "Mo",
    reponse: 2,
    explication: "Le Magnésium s'écrit Mg (Mn étant le Manganèse).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel phénomène produit un dépôt vert-de-gris sur le cuivre exposé à l'air humide ?",
    reponse1: "La nitration",
    reponse2: "La trempe atmosphérique",
    reponse3: "L'oxydation / carbonatation",
    reponse4: "La carburation",
    reponse: 3,
    explication: "Le vert-de-gris résulte d'une oxydation lente combinée au dioxyde de carbone et à l'humidité de l'air.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel métal est le constituant principal du métal d'apport en brasage tendre de tuyauterie ?",
    reponse1: "Le Fer",
    reponse2: "Le Chrome",
    reponse3: "L'Étain",
    reponse4: "Le Titane",
    reponse: 3,
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique de l'Aluminium ?",
    reponse1: "Al",
    reponse2: "Am",
    reponse3: "Au",
    reponse4: "Lm",
    reponse: 1,
    explication: "Le symbole de l'Aluminium est Al (Au étant l'Or).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le rôle du carbone dans la structure cristalline du fer ?",
    reponse1: "Diminuer le poids du métal",
    reponse2: "Rendre le métal transparent aux aimants",
    reponse3: "Augmenter la dureté et la résistance",
    reponse4: "Empêcher le métal de fondre",
    reponse: 3,
    explication: "Les atomes de Carbone viennent se loger dans le réseau atomique du Fer, bloquant les glissements de plans et augmentant la dureté.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel élément d'alliage est ajouté aux aciers pour affiner leur grain et augmenter leur limite d'élasticité ?",
    reponse1: "Le Plomb (Pb)",
    reponse2: "Le Vanadium (V)",
    reponse3: "Le Silicium (Si)",
    reponse4: "Le Nickel (Ni)",
    reponse: 2,
    explication: "Le Vanadium (V) forme des carbures très fins qui empêchent les grains d'acier de grossir.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Quel est le symbole chimique du Vanadium ?",
    reponse1: "Va",
    reponse2: "Vn",
    reponse3: "Vd",
    reponse4: "V",
    reponse: 4,
    explication: "Le symbole du Vanadium est simplement V.",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "L'acier au silicium est principalement utilisé pour ses propriétés :",
    reponse1: "Inoxydables",
    reponse2: "Résistantes à l'abrasion",
    reponse3: "Magnétiques (tôles électriques)",
    reponse4: "D'étanchéité à l'eau",
    reponse: 3,
    explication: "Le Silicium augmente la résistivité électrique et réduit les pertes par hystérésis dans les tôles magnétiques (transformateurs, moteurs).",
    thème: "Chimie",
    global: "tout"
  },
  {
    question: "Comment appelle-t-on l'oxydation noire superficielle qui se forme à chaud sur l'acier laminé ?",
    reponse1: "La calamine",
    reponse2: "La craie",
    reponse3: "La stéatite",
    reponse4: "Le laitier",
    reponse: 1,
    explication: "La calamine est la couche d'oxydes d'un noir mat qui se forme à la surface du métal lors du travail à chaud.",
    thème: "Chimie",
    global: "tout"
  },

  /* Matériaux */
  {
    question: "Pour tarauder à M8 dans de l'acier doux, quel diamètre de foret dois-tu utiliser pour percer ?",
    reponse1: "7,5 mm",
    reponse2: "6,8 mm",
    reponse3: "6,0 mm",
    reponse4: "7,2 mm",
    reponse: 2,
    explication: "Pour tarauder du M8 (pas standard de 1,25 mm), on applique D - Pas = 8 - 1,25 = 6,75 mm, ce qui donne un perçage à 6,8 mm.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quelle est la règle pratique pour calculer le diamètre de perçage avant taraudage (M) ?",
    reponse1: "Diamètre du taraud multiplié par 0,8",
    reponse2: "Diamètre du taraud divisé par 1,5",
    reponse3: "Diamètre du taraud moins le pas (D - P)",
    reponse4: "Diamètre du taraud moins 0,5 mm",
    reponse: 3,
    explication: "La formule universelle en atelier est Ø Foret = Ø Taraud - Pas du filet.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Lors du tronçonnage d'un profilé à la meuleuse, que risque-t-il de se passer si tu pinces le disque dans le trait de coupe ?",
    reponse1: "Le disque éclate / rebond violent de la meuleuse",
    reponse2: "La lame se bloque sans créer de choc",
    reponse3: "Le moteur patine sans endommager le disque",
    reponse4: "Le trait de coupe s'élargit progressivement",
    reponse: 1,
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quand tu plies une tôle à 90° à la presse pliuse, que dois-tu anticiper pour avoir l'angle exact une fois relâchée ?",
    reponse1: "L'allongement de la zone neutre",
    reponse2: "Le fluage du métal",
    reponse3: "L'écroissage de surface",
    reponse4: "Le retour élastique du métal",
    reponse: 4,
    explication: "Le métal a tendance à se déplier légèrement après le retrait du poinçon : il faut accentuer le pliage pour compenser ce retour élastique.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Si tu dois plier une tôle en aluminium de forte épaisseur sans qu'elle ne fissure au pli, que dois-tu respecter ?",
    reponse1: "Plier parallèlement au sens de laminage avec un petit rayon",
    reponse2: "Plier perpendiculairement au sens de laminage et adapter le rayon",
    reponse3: "Refroidir la zone de pliage juste avant déformation",
    reponse4: "Marquer une empreinte profonde au pointeau sur la ligne de pli",
    reponse: 2,
    explication: "Plier perpendiculairement aux fibres de laminage évite l'ouverture de criques et de fissures le long du pli.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Lors du taraudage manuel de l'acier, pourquoi faut-il régulièrement faire un demi-tour en arrière ?",
    reponse1: "Pour briser le copeau et éviter de coincer le taraud",
    reponse2: "Pour réaligner le taraud dans son axe",
    reponse3: "Pour réinjecter l'huile au fond du trou",
    reponse4: "Pour polir les flancs du filet",
    reponse: 1,
    explication: "Le retour arrière casse le copeau continu qui risquerait de s'accumuler et de briser les goujures du taraud.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quel lubrifiant est indispensable lors du vissage ou taraudage de pièces en inox pour éviter le grippage ?",
    reponse1: "Huile minérale fluide SAE 10",
    reponse2: "Graisse/pâte anti-seize ou huile de coupe spéciale inox",
    reponse3: "Dégrippant universel en aérosol",
    reponse4: "Savon liquide d'atelier",
    reponse: 2,
    explication: "L'inox à nu a une forte tendance au grippage à sec (soudate à froid) ; la graisse anti-seize (ou l'huile de coupe lourde) est obligatoire.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Sur le terrain, quelle méthode simple permet de contrôler l'équarrissage d'un grand châssis rectangulaire au mètre ?",
    reponse1: "Mesurer la longueur des quatre côtés extérieurs",
    reponse2: "Mesurer et comparer les deux diagonales",
    reponse3: "Vérifier la hauteur des quatre angles",
    reponse4: "Comparer la largeur au centre et aux extrémités",
    reponse: 2,
    explication: "Un rectangle parfait possède des diagonales rigoureusement égales. Si les diagonales sont identiques, le châssis est d'équerre.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quelle est la règle pour la vitesse de coupe lors du perçage d'un acier doux par rapport à de l'aluminium (foret HSS) ?",
    reponse1: "Tourner à la même vitesse pour les deux matériaux",
    reponse2: "Tourner plus vite dans l'acier que dans l'aluminium",
    reponse3: "Tourner plus lentement dans l'acier et plus vite dans l'aluminium",
    reponse4: "Utiliser la vitesse maximale de la perceuse dans les deux cas",
    reponse: 3,
    explication: "Plus le matériau est dur, plus la vitesse de coupe ($V_c$) doit être basse pour éviter d'échauffer l'outil.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Si ton foret fume et bleuit lors du perçage d'une tôle en acier, quelle en est la cause immédiate ?",
    reponse1: "Une vitesse de rotation trop élevée et un manque de lubrification",
    reponse2: "Une vitesse de rotation trop faible",
    reponse3: "Une pression d'appui trop importante sur le foret",
    reponse4: "Un diamètre de perçage trop petit pour l'épaisseur",
    reponse: 1,
    explication: "Le bleuissement indique un surchauffage thermique dû à une vitesse excessive et à un frottement à sec.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quel disque monte-t-on sur une meuleuse d'angle pour ébavurer une soudure ou meuler du métal ?",
    reponse1: "Un disque à tronçonner fin (1,2 mm)",
    reponse2: "Un disque diamant universel",
    reponse3: "Un disque à ébavurer épais ou un disque à lamelles",
    reponse4: "Un disque en fibre abrasive sans plateau support",
    reponse: 3,
    explication: "Les disques à ébavurer sont renforcés et épais ($\sim 6\ mm$) pour supporter l'effort latéral, contrairement aux disques froids à tronçonner.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Que se passe-t-il si tu utilises un disque à tronçonner très fin (1 mm) pour meuler de côté ?",
    reponse1: "Le disque s'use simplement plus rapidement",
    reponse2: "Le disque risque de se voiler sans casser",
    reponse3: "La meuleuse perd en puissance de rotation",
    reponse4: "Le disque risque de se disloquer et d'éclater",
    reponse: 4,
    explication: "La structure d'un disque fin de 1 mm n'est pas conçue pour subir des efforts radiaux/latéraux : il casse sous l'effort latéral.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Pour tracer une ligne de coupe nette sur de l'acier brut ou calaminé, quel outil d'atelier utilise-t-on ?",
    reponse1: "Un pointeau",
    reponse2: "Une pointe à tracer",
    reponse3: "Un régleur optique",
    reponse4: "Un marqueur peinture large",
    reponse: 2,
    explication: "La pointe à tracer en carbure gravure une ligne très fine et indélébile dans la couche d'oxyde ou de surface du métal.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Pourquoi marque-t-on un coup de pointeau avant de percer au foret sur du métal ?",
    reponse1: "Pour marquer la profondeur finale du perçage",
    reponse2: "Pour amorcer le débouchage du trou",
    reponse3: "Pour guider la pointe du foret et éviter qu'il ne ripe",
    reponse4: "Pour décompresser la matière avant l'usinage",
    reponse: 3,
    explication: "La pointe d'amorce du foret a besoin d'un cône de guidage pour ne pas 'se promener' sur la surface métallique plane.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quelle est l'application de la règle géométrique 3-4-5 lors du traçage d'une structure ?",
    reponse1: "Trouver le centre exact d'une pièce circulaire",
    reponse2: "Tracer un angle droit parfait de grand gabarit",
    reponse3: "Calculer l'allongement d'un profilé au pliage",
    reponse4: "Déterminer la tolérance d'assemblage d'un châssis",
    reponse: 2,
    explication: "Basée sur le théorème de Pythagore ($3^2 + 4^2 = 5^2$), cette règle assure la création d'un angle à $90^\circ$ parfait.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "En traçage manuel, quel outil permet de tracer et retrouver rapidement le centre d'un rond en acier ?",
    reponse1: "Une équerre à centrer",
    reponse2: "Un trusquin d'épaisseur",
    reponse3: "Un rapporteur d'angle d'atelier",
    reponse4: "Un jauge de profondeur",
    reponse: 1,
    explication: "L'équerre à centrer possède une règle bissectrice qui passe toujours par le centre du cylindre appuyé sur son V.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Lors d'un assemblage par rivet aveugle (POP), comment doit être ajusté le diamètre de perçage par rapport au rivet ?",
    reponse1: "Percer exactement au même diamètre sans aucun jeu",
    reponse2: "Percer avec un jeu de 0,1 mm à 0,2 mm de plus que le rivet",
    reponse3: "Percer avec un jeu de 1,0 mm de plus que le rivet",
    reponse4: "Percer légèrement en dessous du diamètre du rivet",
    reponse: 2,
    explication: "Un léger jeu (+0,1 à +0,2 mm) permet d'insérer le rivet facilement tout en garantissant qu'il gonfle correctement lors du serrage.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Lors de la coupe d'un tube carré à la scie à ruban, quel geste évite d'ébrécher les dents de la lame ?",
    reponse1: "Augmenter la vitesse de descente au contact de l'arête",
    reponse2: "Modérer la vitesse de descente lors de l'attaque des arêtes",
    reponse3: "Couper à sec sans fluide d'usinage",
    reponse4: "Inverser le sens de défilement du ruban au démarrage",
    reponse: 2,
    explication: "Les arêtes vives d'un profilé appliquent une charge ponctuelle énorme sur les dents du ruban : il faut ralentir l'amorce de coupe.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Quelle est la fonction principale du fluide de coupe soluble lors du perçage ou sciage de l'acier ?",
    reponse1: "Dissoudre les micro-bavures d'usinage",
    reponse2: "Augmenter la dureté de l'outil pendant la coupe",
    reponse3: "Refroidir l'outil, lubrifier et faciliter l'évacuation des copeaux",
    reponse4: "Passiver la surface de la pièce contre la rouille instantanée",
    reponse: 3,
    explication: "Le fluide de coupe abaisse la température au point de contact, évite le collage de la matière et balaye les copeaux.",
    thème: "Matériaux",
    global: "tout"
  },
  {
    question: "Comment élimine-t-on les bavures coupantes à l'entrée ou sortie d'un trou percé ?",
    reponse1: "En utilisant un outil ébavureur ou un foret de plus grand diamètre tourné à la main",
    reponse2: "En meulant la zone avec un disque à tronçonner fin",
    reponse3: "En martelant la bordure du trou avec un pointeau",
    reponse4: "En repassant le foret d'origine à vitesse maximale",
    reponse: 1,
    explication: "Un coup d'ébavureur manivelle ou un léger chanfrein à la main au gros foret casse l'arête vive rapidement et proprement.",
    thème: "Matériaux",
    global: "tout"
  },

  /* Soudure */
  {
    question: "Quelle est la principale différence entre le procédé MIG et le procédé MAG ?",
    reponse1: "Le MIG utilise de l'air comprimé, le MAG utilise de l'argon pur",
    reponse2: "Le MIG utilise un gaz inerte (ex: Argon), le MAG un gaz actif (ex: CO2)",
    reponse3: "Le MIG est réservé à l'acier doux, le MAG à l'aluminium",
    reponse4: "Le MIG fonctionne en courant continu, le MAG en courant alternatif",
    reponse: 2,
    explication: "MIG = Metal Inert Gas (Argon, Hélium). MAG = Metal Active Gas (Mélange Argon + CO2 / O2 qui réagit chimiquement avec le bain).",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel gaz est le plus fréquemment utilisé comme gaz de protection pur en soudage TIG ?",
    reponse1: "Le Dioxyde de carbone ($CO_2$)",
    reponse2: "L'Azote ($N_2$)",
    reponse3: "L'Argon (Ar)",
    reponse4: "L'Hélium pur",
    reponse: 3,
    explication: "L'Argon pur est le gaz universel en TIG car il est totalement inerte et protège le tungstène et le bain de fusion.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En soudage TIG de l'aluminium, quel type de courant doit-on impérativement utiliser ?",
    reponse1: "Courant alternatif (AC)",
    reponse2: "Courant continu polarité directe (DC-)",
    reponse3: "Courant continu polarité inverse (DC+)",
    reponse4: "Courant pulsé haute fréquence uniquement",
    reponse: 1,
    explication: "Le courant alternatif (AC) est indispensable : la demi-onde positive décape l'alumine (oxyde), tandis que la demi-onde négative pénètre.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Comment appelle-t-on le résidu solide qui recouvre le cordon après un soudage à l'électrode enrobée (MMA) ?",
    reponse1: "La calamine",
    reponse2: "Le laitier",
    reponse3: "L'oxyde de surface",
    reponse4: "Le chanfrein",
    reponse: 2,
    explication: "L'enrobage en fondant forme le laitier, une croûte protectrice solide qui s'élimine au marteau à piquer.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En soudage MIG/MAG, que se passe-t-il si le débit de gaz de protection est trop faible ou coupé ?",
    reponse1: "Le fil de soudure se bloque instantanément dans la torche",
    reponse2: "L'arc électrique devient trop chaud et perce la pièce",
    reponse3: "Apparition d'une forte porosité (bulles/trous) dans le cordon",
    reponse4: "Le poste se met en sécurité thermique",
    reponse: 3,
    explication: "L'air ambiant s'infiltre dans le bain en fusion et crée des pores (bulles de gaz emprisonnées).",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel est l'angle de chanfrein le plus courant préparé sur les bords de tôles épaisses à souder en bout à bout ?",
    reponse1: "90° (45° par tôle)",
    reponse2: "30° (15° par tôle)",
    reponse3: "60° (30° par tôle)",
    reponse4: "45° (22,5° par tôle)",
    reponse: 3,
    explication: "Le chanfrein en V standard est ouvert à $60^\circ$ au total (soit $30^\circ$ de chanfrein sur chaque tôle).",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel métal compose l'électrode réfractaire (non fusible) utilisée en soudage TIG ?",
    reponse1: "Le Titane",
    reponse2: "Le Tungstène",
    reponse3: "Le Molybdène",
    reponse4: "Le Graphite",
    reponse: 2,
    explication: "Grâce à son point de fusion extrêmement élevé ($3 422\ ^\circ C$), le Tungstène conduit l'arc sans fondre.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En soudage MMA à l'électrode basique, pourquoi est-il recommandé d'étuver (chauffer) les électrodes avant emploi ?",
    reponse1: "Pour faciliter l'amorçage de l'arc à froid",
    reponse2: "Pour éliminer l'humidité et éviter la fissuration par l'hydrogène",
    reponse3: "Pour ramollir l'enrobage et rendre le laitier plus fluide",
    reponse4: "Pour augmenter l'intensité du courant de soudage",
    reponse: 2,
    explication: "L'enrobage basique capte très vite l'humidité de l'air ; le séchage au four évite les inclusions d'hydrogène responsables de fissures à froid.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel défaut de soudure désigne le manque de fusion entre le métal déposé et le métal de base ?",
    reponse1: "Une morsure",
    reponse2: "Une retassure",
    reponse3: "Un collage",
    reponse4: "Une soufflure",
    reponse: 3,
    explication: "Le collage se produit lorsque le métal d'apport s'est déposé sans fondre véritablement la surface de la pièce support.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En soudage MAG de l'acier carbone, quel mélange de gaz courant utilise-t-on le plus souvent ?",
    reponse1: "100 % CO2 pur",
    reponse2: "Argon + CO2 (ex: 82% Ar / 18% CO2)",
    reponse3: "Argon + Hélium (50/50)",
    reponse4: "Argon + 2% d'Oxygène",
    reponse: 2,
    explication: "Le mélange Argon + 15 à 18 % CO2 offre un bon compromis entre pénétration et réduction des projections.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel est le rôle principal du flux présent au cœur d'un fil fourré sans gaz (FCAW) ?",
    reponse1: "Générer son propre gaz et son laitier de protection lors de la fusion",
    reponse2: "Refroidir la buse de la torche pendant le soudage",
    reponse3: "Faciliter l'entraînement du fil dans les galets du dévidoir",
    reponse4: "Augmenter la vitesse d'avance du fil",
    reponse: 1,
    explication: "À la manière d'une électrode MMA inversée, la poudre interne du fil fourré brûle et dégage la protection gazeuse.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Que risque-t-on si l'intensité (l'ampérage) réglée sur le poste est beaucoup trop élevée pour l'épaisseur de tôle ?",
    reponse1: "Un manque de pénétration et un cordon bombé",
    reponse2: "Un effondrement du bain de fusion / perçage de la pièce",
    reponse3: "Une usure prématurée du galet de dévidoir",
    reponse4: "L'extinction automatique de l'arc",
    reponse: 2,
    explication: "Trop d'ampérage apporte trop de chaleur : la tôle fond intégralement et s'effondre (effet de trou de serrure non contrôlé).",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel équipement de protection est indispensable pour protéger les yeux contre les rayons UV de l'arc ?",
    reponse1: "Des lunettes de sécurité transparentes amovibles",
    reponse2: "Visère en polycarbonate teintée catégorie 3",
    reponse3: "Un masque de soudage avec verre opacifiant adapté (ex: DIN 9 à 13)",
    reponse4: "Des lunettes d'oxycoupage (teinte DIN 5)",
    reponse: 3,
    explication: "Seul un filtre ou verre de soudage opacifié (norme DIN 9 à 13 selon l'ampérage) stoppe les UV nocifs responsables du 'coup d'arc'.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Comment appelle-t-on la déformation d'une structure causée par le refroidissement du métal de soudure ?",
    reponse1: "L'écroissage",
    reponse2: "Le retrait",
    reponse3: "Le fluage",
    reponse4: "Le matage",
    reponse: 2,
    explication: "En se refroidissant, le métal de soudure se contracte : ce phénomène crée des forces de retrait qui tirent et déforment la pièce.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel est le rôle du 'Post-gaz' en soudage TIG ?",
    reponse1: "Purger la torche avant l'allumage de l'arc",
    reponse2: "Protéger le Tungstène et le bain de l'oxydation pendant leur refroidissement",
    reponse3: "Refroidir le câble de masse",
    reponse4: "Accélérer l'extinction de l'arc électrique",
    reponse: 2,
    explication: "Le gaz continue de couler après l'extinction de l'arc pour éviter que la pointe de tungstène encore rouge ne s'oxyde au contact de l'air.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En soudage TIG, quelle couleur d'anneau caractérise généralement une électrode au Tungstène pur ?",
    reponse1: "Rouge",
    reponse2: "Bleu",
    reponse3: "Vert",
    reponse4: "Gris",
    reponse: 3,
    explication: "Le code couleur pour le Tungstène pur (sans terre rare ni oxyde) est le Vert.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Que désigne le terme 'morsure' (ou caniveau) sur les bords d'un cordon de soudure ?",
    reponse1: "Un creux dans le métal de base non rempli sur le bord du cordon",
    reponse2: "Une inclusion de laitier emprisonnée sous la passe",
    reponse3: "Une fissure longitudinale au milieu du cordon",
    reponse4: "Une surépaisseur trop importante du métal d'apport",
    reponse: 1,
    explication: "La morsure est une entaille creusée dans la pièce par la chaleur de l'arc et qui n'a pas été rechargée par le métal d'apport.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Pourquoi effectue-t-on un 'inertage' de tuyauterie en inox lors du soudage TIG ?",
    reponse1: "Pour nettoyer la graisse restante à l'intérieur du tube",
    reponse2: "Pour éviter 'l'rocherage' (l'oxydation lourde de la racine à l'intérieur)",
    reponse3: "Pour accélérer le refroidissement de la tuyauterie",
    reponse4: "Pour vérifier l'étanchéité de la conduite sous pression",
    reponse: 2,
    explication: "Sans gaz inerte à l'intérieur du tube, la racine de soudure exposée à l'air brûle et forme une structure poreuse appelée 'rocherage'.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quelle méthode CND permet de détecter facilement les micro-fissures ouvertes en surface ?",
    reponse1: "La magnétoscopie sur inox",
    reponse2: "Le contrôle par ressuage (pénétrant + révélateur)",
    reponse3: "L'essai d'étanchéité à l'air comprimé",
    reponse4: "La mesure de dureté Rockwell",
    reponse: 2,
    explication: "Le produit pénétrant s'infiltre dans les défauts de surface, puis le révélateur buvard fait ressortir le défaut en couleur contrastée.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel type d'enrobage d'électrode MMA offre la meilleure résistance aux chocs et fissures ?",
    reponse1: "Rutile",
    reponse2: "Basique",
    reponse3: "Cellulosique",
    reponse4: "Acide",
    reponse: 2,
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Quel type d'enrobage d'électrode MMA est le plus facile à amorcer et le plus répandu en atelier courant ?",
    reponse1: "Basique",
    reponse2: "Rutile",
    reponse3: "Cellulosique",
    reponse4: "Acide",
    reponse: 2,
    explication: "L'électrode Rutile offre une grande stabilité d'arc et un réamorçage très facile pour les soudures courantes.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Que caractérise le régime de transfert 'Short-arc' (par court-circuit) en MIG/MAG ?",
    reponse1: "Un transfert par gouttelettes très fines projetées à fort ampérage",
    reponse2: "Un transfert où le fil touche le bain, crée un court-circuit et dépose une goutte à basse énergie",
    reponse3: "Un arc qui tourne en cercle autour du fil d'apport",
    reponse4: "Un transfert sans aucun contact entre le fil et la pièce",
    reponse: 2,
    explication: "Le régime Short-arc travaille à basse tension : le fil plonge dans le liquide, s'y isole par court-circuit et détache la goutte.",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "Dans le procédé de soudage oxyacéthylénique (chalumeau), quels sont les deux gaz mélangés ?",
    reponse1: "Oxygène et Propanol",
    reponse2: "Oxygène et Acéthylène",
    reponse3: "Argon et Acéthylène",
    reponse4: "Azote et Hydrogène",
    reponse: 2,
    explication: "La combustion d'Oxygène et d'Acéthylène produit la flamme la plus chaude utilisable en atelier ($\sim 3 100\ ^\circ C$).",
    thème: "Soudure",
    global: "tout"
  },
  {
    question: "En MIG/MAG, à quoi sert principalement le réglage de la tension (en Volts) sur le poste ?",
    reponse1: "Régler la vitesse d'avance du fil de soudure",
    reponse2: "Déterminer la longueur de l'arc et la largeur du cordon",
    reponse3: "Changer la fréquence d'impulsion du courant",
    reponse4: "Ajuster automatiquement le débit de gaz",
    reponse: 2,
    explication: "La tension (Volts) ajuste directement la hauteur de l'arc : plus elle augmente, plus l'arc s'élargit et plus le cordon s'étale.",
    thème: "Soudure",
    global: "tout"
  },

  /* Thermique */
  {
    question: "Quel procédé thermique consiste à chauffer l'acier puis à le refroidir très rapidement pour augmenter sa dureté ?",
    reponse1: "La revenue",
    reponse2: "Le recuit",
    reponse3: "La trempe",
    reponse4: "Le forgeage",
    reponse: 3,
    explication: "La trempe est l'opération de refroidissement rapide destinée à piéger le carbone et créer de la martensite.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel est l'objectif principal du traitement thermique de trempe sur un acier au carbone ?",
    reponse1: "Rendre l'acier plus ductile et facile à plier",
    reponse2: "Augmenter considérablement sa dureté et sa résistance à l'usure",
    reponse3: "Améliorer sa conductivité électrique",
    reponse4: "Diminuer sa masse volumique pour l'alléger",
    reponse: 2,
    explication: "La trempe fige la structure sous forme extrêmement dure (martensite) au détriment de sa ductilité.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Pourquoi effectue-t-on systématiquement un 'revenu' immédiatement après avoir trempé une pièce en acier ?",
    reponse1: "Pour éliminer les contraintes internes et réduire la fragilité excessive",
    reponse2: "Pour augmenter encore plus la dureté obtenue à la trempe",
    reponse3: "Pour protéger la surface contre la rouille instantanée",
    reponse4: "Pour restituer à l'acier sa couleur d'origine",
    reponse: 1,
    explication: "Une pièce brute de trempe est 'cassante comme du verre'. Le revenu redonne de la ténacité en relâchant les tensions.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Commentappelle-t-on le traitement thermique qui consiste à chauffer l'acier puis à le laisser refroidir très lentement au four ?",
    reponse1: "La trempe sous vide",
    reponse2: "Le revenu à haute température",
    reponse3: "Le recuit",
    reponse4: "La nitruration",
    reponse: 3,
    explication: "Le recuit vise à adoucir l'acier, affiner le grain ou supprimer l'écroissage en refroidissant très progressivement.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel milieu de refroidissement refroidit l'acier le plus brutalement lors d'une trempe ?",
    reponse1: "L'huile minérale spéciale trempe",
    reponse2: "L'air calme à température ambiante",
    reponse3: "L'eau salée (ou eau additionnée de soude)",
    reponse4: "Le bain de plomb fondu",
    reponse: 3,
    explication: "L'eau salée dissipe la couche de vapeur (caléfaction) beaucoup plus vite que l'huile ou l'air, provoquant un choc thermique maximal.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Sur le terrain, à quelle couleur de chauffe visuelle correspond environ la température d'austénitisation de l'acier ($\sim 800\ ^\circ C$ à $850\ ^\circ C$) ?",
    reponse1: "Rouge cerise / rouge clair",
    reponse2: "Jaune paille",
    reponse3: "Bleu nuit",
    reponse4: "Blanc étincelant",
    reponse: 1,
    explication: "Le rouge cerise net indique qu'on a dépassé le point critique $A_3$ d'austénitisation nécessaire avant d'immerger.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quelle méthode physique très simple à l'aimant permet de savoir si une pièce en acier a atteint sa température de trempe ?",
    reponse1: "L'acier devient amagnétique (perte de l'attraction de l'aimant)",
    reponse2: "L'acier attire l'aimant deux fois plus fort",
    reponse3: "L'aimant se colle définitivement à la pièce",
    reponse4: "L'acier repousse l'aimant comme deux pôles identiques",
    reponse: 1,
    explication: "Au passage du point de Curie ($\sim 770\ ^\circ C$), la structure passe en phase austénitique amagnétique.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Comment s'appelle la structure cristalline ultra dure et fragile obtenue directement après le refroidissement rapide d'une trempe ?",
    reponse1: "La ferrite",
    reponse2: "La perlite",
    reponse3: "La martensite",
    reponse4: "L'austénite",
    reponse: 3,
    explication: "La martensite est la phase métastable hors d'équilibre obtenue quand le carbone n'a pas eu le temps de diffuser lors du refroidissement.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel risque majeur prend-on si l'on refroidit une pièce complexe à sections inégales trop brutalement à l'eau lors de la trempe ?",
    reponse1: "Un risque élevé de tapures (fissures de trempe) ou de déformation lourde",
    reponse2: "Un risque de fonte intégrale des arêtes fines",
    reponse3: "Une perte complète du taux de carbone dans la pièce",
    reponse4: "Un gonflement de la pièce qui double de volume",
    reponse: 1,
    explication: "Les angles et sections fines refroidissent plus vite que les masses, générant des écarts de dilatation extrêmes qui crique le métal (tapure).",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "En atelier, à quelle température approximative correspond la teinte d'oxydation 'Jaune paille' lors d'un revenu d'outil sur acier polie ?",
    reponse1: "Environ $150\ ^\circ C$",
    reponse2: "Environ $220\ ^\circ C$ à $240\ ^\circ C$",
    reponse3: "Environ $300\ ^\circ C$ à $320\ ^\circ C$",
    reponse4: "Plus de $450\ ^\circ C$",
    reponse: 2,
    explication: "La couleur d'oxydation jaune paille apparaît entre $220\ ^\circ C$ et $240\ ^\circ C$ et conserve la dureté maximale pour les outils de coupe.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Pour un burin ou un outil de coupe manuel en acier au carbone, quelle teinte de revenu recherche-t-on sur le tranchant ?",
    reponse1: "Bleu foncé (très doux)",
    reponse2: "Gris métallisé (aucun revenu)",
    reponse3: "Jaune paille / brun (dureté élevée conservée)",
    reponse4: "Rouge sombre",
    reponse: 3,
    explication: "La nuance jaune/brune garantit un tranchant très dur, tout en soulageant la fragilité extrême post-trempe.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Peut-on tremper efficacement un acier doux de type S235 (contient $\sim 0,15\ \%$ de carbone) ?",
    reponse1: "Oui, il devient aussi dur qu'un acier à outil",
    reponse2: "Non, son taux de carbone est trop faible pour former de la martensite",
    reponse3: "Oui, mais uniquement si on le trempe dans de l'huile froide",
    reponse4: "Oui, à condition de le chauffer au blanc à $1200\ ^\circ C$",
    reponse: 2,
    explication: "Il faut au moins 0,3 % à 0,35 % de Carbone pour tremper un acier. En dessous, la trempe n'a quasiment aucun effet durcissant.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Comment appelle-t-on le traitement thermochimique qui consiste à enrichir la surface d'un acier doux en carbone avant trempe ?",
    reponse1: "La cémentation",
    reponse2: "Le revenu secondaire",
    reponse3: "La phosphatation",
    reponse4: "Le démagnétisme",
    reponse: 1,
    explication: "La cémentation apporte du carbone en surface par diffusion à chaud pour former une couche superficielle trempable.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel traitement thermochimique permet de durcir la surface d'une pièce en y diffusant de l'azote à basse température ($\sim 500\ ^\circ C$) ?",
    reponse1: "La nitruration",
    reponse2: "La carburation liquide",
    reponse3: "La galvanisation à chaud",
    reponse4: "Le chromage dur",
    reponse: 1,
    explication: "La nitruration diffuse de l'Azote pour former des nitrures ultrafins et extrêmement durs en surface.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel est l'avantage principal de la nitruration par rapport à une cémentation suivie d'une trempe classique ?",
    reponse1: "Elle ne nécessite pas de trempe ultérieure, évitant ainsi les déformations de pièces",
    reponse2: "Elle permet de diviser par deux le poids final de la pièce",
    reponse3: "Elle rend l'acier totalement transparent aux ultrasons",
    reponse4: "Elle s'effectue en quelques secondes seulement",
    reponse: 1,
    explication: "Puisqu'il n'y a pas de choc thermique de trempe après la nitruration, les pièces ne voilent pas et conservent leurs cotes d'usinage.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Lors de la trempe d'une pièce longue et fine (ex: une broche ou une lame), quel geste évite de la voiler lors de l'immersion ?",
    reponse1: "Plonger la pièce horizontalement à grande vitesse",
    reponse2: "Plonger la pièce parfaitement verticalement dans le bac de trempe",
    reponse3: "Faire tourner la pièce en cercle dans le liquide",
    reponse4: "Attendre que la pièce soit entièrement refroidie à l'air avant d'immerger",
    reponse: 2,
    explication: "L'immersion verticale refroidit les deux faces de manière parfaitement symétrique, éliminant les flexions thermiques latérales.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "À quoi sert un recuit de libération de contraintes (ou recuit de détensionnement) après du soudage ou de l'usinage lourd ?",
    reponse1: "Éliminer les tensions internes sans modifier profondément la structure ni la dureté",
    reponse2: "Faire fondre les bavures d'usinage restantes",
    reponse3: "Augmenter la teneur en carbone du cordon de soudure",
    reponse4: "Changer la teinte de la pièce pour un contrôle visuel",
    reponse: 1,
    explication: "Ce chauffage modéré relâche les déformations plastiques et blocages internes accumulés pendant le travail mécanique sans détremper brusquement.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quelle teinte d'oxydation indique un revenu à haute température ($\sim 300\ ^\circ C$), adapté aux ressorts ou outils devant absorber des chocs ?",
    reponse1: "Jaune clair",
    reponse2: "Bleu / bleu violet",
    reponse3: "Brun paille",
    reponse4: "Vert olive",
    reponse: 2,
    explication: "Le bleu correspond à un revenu poussé autour de $300\ ^\circ C$ : la dureté diminue mais l'élasticité et la résistance aux chocs deviennent maximales.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Que se passe-t-il si l'on surchauffe un acier bien au-delà de sa température de trempe (ex: $> 1100\ ^\circ C$) pendant trop longtemps ?",
    reponse1: "Le grain grossit fortement, rendant l'acier plus fragile après trempe (brûlure du métal)",
    reponse2: "L'acier devient définitivement incassable",
    reponse3: "La pièce se transforme automatiquement en inox",
    reponse4: "Le carbone s'évapore et la pièce devient en aluminium",
    reponse: 1,
    explication: "La surchauffe fait grossir les grains d'austénite : après trempe, la martensite obtenue sera à gros grain et très fragile.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "En trempe par induction, comment la chaleur est-elle générée au cœur de la pièce ?",
    reponse1: "Par des brûleurs à gaz haute pression orientés sur la pièce",
    reponse2: "Par des courants de Foucault induits à haute fréquence à la surface du métal",
    reponse3: "Par immersion dans des sels en fusion à $900\ ^\circ C$",
    reponse4: "Par friction mécanique à haute vitesse",
    reponse: 2,
    explication: "L'inducteur en cuivre crée un champ magnétique alternatif qui génère des courants de Foucault et chauffe la surface par effet Joule très rapidement.",
    thème: "Thermique",
    global: "tout"
  },
  {
    question: "Quel est l'intérêt principal de la trempe par induction par rapport à une trempe globale au four ?",
    reponse1: "Elle permet de durcir uniquement la couche superficielle tout en gardant un cœur ductile",
    reponse2: "Elle fonctionne sans consommer d'énergie électrique",
    reponse3: "Elle permet de tremper du plastique et du bois",
    reponse4: "Elle élimine le besoin de nettoyer la pièce après traitement",
    reponse: 1,
    explication: "La montée en température très rapide et localisée permet d'obtenir un pli dur et résistant à l'usure en surface tout en préservant la ténacité du cœur.",
    thème: "Thermique",
    global: "tout"
  }
];